/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BulkCreateEventsDto { 
    datetime?: string;
    context: BulkCreateEventsDto.ContextEnum;
    gameId?: string;
    roundId?: string;
    playerIds: Array<string>;
    eventTypeId: string;
}
export namespace BulkCreateEventsDto {
    export type ContextEnum = 'GAME' | 'ROUND';
    export const ContextEnum = {
        Game: 'GAME' as ContextEnum,
        Round: 'ROUND' as ContextEnum
    };
}


