/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateGameDto { 
    datetime?: string;
    completed?: boolean;
    placeType: CreateGameDto.PlaceTypeEnum;
    hostedById?: string;
    placeOfAwayGame?: string;
}
export namespace CreateGameDto {
    export type PlaceTypeEnum = 'HOME' | 'AWAY' | 'REMOTE';
    export const PlaceTypeEnum = {
        Home: 'HOME' as PlaceTypeEnum,
        Away: 'AWAY' as PlaceTypeEnum,
        Remote: 'REMOTE' as PlaceTypeEnum
    };
}


