/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreatePenaltyDto } from './createPenaltyDto';


export interface CreateEventTypeDto { 
    createDateTime?: string;
    lastChangedDateTime?: string;
    description: string;
    context: CreateEventTypeDto.ContextEnum;
    trigger?: CreateEventTypeDto.TriggerEnum;
    penalty?: CreatePenaltyDto;
    multiplicatorUnit?: string;
    hasComment?: boolean;
}
export namespace CreateEventTypeDto {
    export type ContextEnum = 'GAME' | 'ROUND';
    export const ContextEnum = {
        Game: 'GAME' as ContextEnum,
        Round: 'ROUND' as ContextEnum
    };
    export type TriggerEnum = 'VERLOREN' | 'SCHOCK_AUS' | 'SCHOCK_AUS_STRAFE' | 'ZWEI_ZWEI_EINS' | 'LUSTWURF';
    export const TriggerEnum = {
        Verloren: 'VERLOREN' as TriggerEnum,
        SchockAus: 'SCHOCK_AUS' as TriggerEnum,
        SchockAusStrafe: 'SCHOCK_AUS_STRAFE' as TriggerEnum,
        ZweiZweiEins: 'ZWEI_ZWEI_EINS' as TriggerEnum,
        Lustwurf: 'LUSTWURF' as TriggerEnum
    };
}


