/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventTypeOverviewDto { 
    id: string;
    description: string;
    context: EventTypeOverviewDto.ContextEnum;
    trigger?: EventTypeOverviewDto.TriggerEnum;
    penaltyValue?: number;
    penaltyUnit?: EventTypeOverviewDto.PenaltyUnitEnum;
    multiplicatorUnit?: string;
    hasComment: boolean;
    eventCount?: number;
}
export namespace EventTypeOverviewDto {
    export type ContextEnum = 'GAME' | 'ROUND';
    export const ContextEnum = {
        Game: 'GAME' as ContextEnum,
        Round: 'ROUND' as ContextEnum
    };
    export type TriggerEnum = 'START_NEW_ROUND' | 'SCHOCK_AUS' | 'SCHOCK_AUS_PENALTY';
    export const TriggerEnum = {
        StartNewRound: 'START_NEW_ROUND' as TriggerEnum,
        SchockAus: 'SCHOCK_AUS' as TriggerEnum,
        SchockAusPenalty: 'SCHOCK_AUS_PENALTY' as TriggerEnum
    };
    export type PenaltyUnitEnum = 'EURO' | 'BEER_CRATE';
    export const PenaltyUnitEnum = {
        Euro: 'EURO' as PenaltyUnitEnum,
        BeerCrate: 'BEER_CRATE' as PenaltyUnitEnum
    };
}


