/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CountByNameDto } from './countByNameDto';
import { SchockAusEffectivityTableDto } from './schockAusEffectivityTableDto';
import { RecordsPerGameDto } from './recordsPerGameDto';


export interface EventTypesStatisticsResponseDto { 
    recordsPerGame: Array<RecordsPerGameDto>;
    eventTypeCounts: Array<CountByNameDto>;
    schockAusEffectivityTable: Array<SchockAusEffectivityTableDto>;
}

