/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventTypeDetailDto } from './eventTypeDetailDto';


export interface EventDetailDto { 
    id: string;
    datetime: string;
    multiplicatorValue: number;
    penaltyValue?: number;
    penaltyUnit?: EventDetailDto.PenaltyUnitEnum;
    comment: string;
    context: EventDetailDto.ContextEnum;
    playerId: string;
    eventType: EventTypeDetailDto;
}
export namespace EventDetailDto {
    export type PenaltyUnitEnum = 'EURO' | 'BEER_CRATE';
    export const PenaltyUnitEnum = {
        Euro: 'EURO' as PenaltyUnitEnum,
        BeerCrate: 'BEER_CRATE' as PenaltyUnitEnum
    };
    export type ContextEnum = 'GAME' | 'ROUND';
    export const ContextEnum = {
        Game: 'GAME' as ContextEnum,
        Round: 'ROUND' as ContextEnum
    };
}


