/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StreakDto } from './streakDto';


export interface EventTypeStreakDto { 
    eventTypeId: string;
    description: string;
    mode: EventTypeStreakDto.ModeEnum;
    streaks: Array<StreakDto>;
}
export namespace EventTypeStreakDto {
    export type ModeEnum = 'WITH_EVENT' | 'WITHOUT_EVENT';
    export const ModeEnum = {
        WithEvent: 'WITH_EVENT' as ModeEnum,
        WithoutEvent: 'WITHOUT_EVENT' as ModeEnum
    };
}


