/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventTypeDetailDto { 
    id: string;
    description: string;
    trigger?: EventTypeDetailDto.TriggerEnum;
    multiplicatorUnit?: string;
}
export namespace EventTypeDetailDto {
    export type TriggerEnum = 'VERLOREN' | 'SCHOCK_AUS' | 'SCHOCK_AUS_STRAFE' | 'ZWEI_ZWEI_EINS' | 'LUSTWURF';
    export const TriggerEnum = {
        Verloren: 'VERLOREN' as TriggerEnum,
        SchockAus: 'SCHOCK_AUS' as TriggerEnum,
        SchockAusStrafe: 'SCHOCK_AUS_STRAFE' as TriggerEnum,
        ZweiZweiEins: 'ZWEI_ZWEI_EINS' as TriggerEnum,
        Lustwurf: 'LUSTWURF' as TriggerEnum
    };
}


