/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoundCountByGameIdDto } from './roundCountByGameIdDto';
import { CountDto } from './countDto';


export interface GamesAndRoundsStatisticsResponseDto { 
    countGames: CountDto;
    countRounds: CountDto;
    averageRoundsPerGame: CountDto;
    maxRoundsPerGame: RoundCountByGameIdDto;
}

