/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PenaltyDto } from './penaltyDto';
import { PlaceDto } from './placeDto';


export interface GameOverviewDto { 
    id: string;
    datetime: string;
    completed: boolean;
    excludeFromStatistics: boolean;
    place: PlaceDto;
    roundCount: number;
    penalties: Array<PenaltyDto>;
}

