/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoundDto } from './roundDto';
import { EventDto } from './eventDto';
import { PlaceDto } from './placeDto';


export interface GameDto { 
    id: string;
    createDateTime: string;
    lastChangedDateTime: string;
    datetime: string;
    completed: boolean;
    excludeFromStatistics: boolean;
    place?: PlaceDto;
    rounds?: Array<RoundDto>;
    events?: Array<EventDto>;
}

