/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HostsTableDto { 
    rank: number;
    hostedById: string | null;
    name?: string;
    placeType: HostsTableDto.PlaceTypeEnum;
    count: number;
}
export namespace HostsTableDto {
    export type PlaceTypeEnum = 'HOME' | 'AWAY' | 'REMOTE';
    export const PlaceTypeEnum = {
        Home: 'HOME' as PlaceTypeEnum,
        Away: 'AWAY' as PlaceTypeEnum,
        Remote: 'REMOTE' as PlaceTypeEnum
    };
}


