/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PenaltyDto } from './penaltyDto';
import { PenaltyByPlayerTableDto } from './penaltyByPlayerTableDto';
import { LiveGamePointsTableDto } from './liveGamePointsTableDto';
import { SchockAusStreakDto } from './schockAusStreakDto';
import { CountDto } from './countDto';
import { RecordsPerGameDto } from './recordsPerGameDto';


export interface LiveGameStatisticsResponseDto { 
    penaltySum: Array<PenaltyDto>;
    euroPerRound: CountDto;
    penaltyByPlayerTable: Array<PenaltyByPlayerTableDto>;
    schockAusStreak: SchockAusStreakDto;
    recordsPerGame: Array<RecordsPerGameDto>;
    pointsTable: Array<LiveGamePointsTableDto>;
}

