/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentDto { 
    id: string;
    createDateTime: string;
    lastChangedDateTime: string;
    penaltyUnit: PaymentDto.PenaltyUnitEnum;
    penaltyValue: number;
    outstandingValue: number;
    confirmed: boolean;
    confirmedBy: string | null;
    gameId: string;
    playerId: string;
    name: string;
    dueDate?: string;
}
export namespace PaymentDto {
    export type PenaltyUnitEnum = 'EURO' | 'BEER_CRATE';
    export const PenaltyUnitEnum = {
        Euro: 'EURO' as PenaltyUnitEnum,
        BeerCrate: 'BEER_CRATE' as PenaltyUnitEnum
    };
}


