/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MostExpensiveGameDto } from './mostExpensiveGameDto';
import { PenaltyDto } from './penaltyDto';
import { PenaltyByPlayerTableDto } from './penaltyByPlayerTableDto';
import { MostExpensiveRoundDto } from './mostExpensiveRoundDto';
import { MostExpensiveRoundAveragePerGameDto } from './mostExpensiveRoundAveragePerGameDto';
import { CountDto } from './countDto';


export interface PenaltyStatisticsResponseDto { 
    penaltySum: Array<PenaltyDto>;
    euroPerGame: CountDto;
    euroPerRound: CountDto;
    mostExpensiveRound: MostExpensiveRoundDto;
    mostExpensiveGame: MostExpensiveGameDto;
    mostExpensiveRoundAveragePerGame: MostExpensiveRoundAveragePerGameDto;
    penaltyByPlayerTable: Array<PenaltyByPlayerTableDto>;
}

