/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlaceDto { 
    type: PlaceDto.TypeEnum;
    hostedById?: string;
    locationLabel?: string;
}
export namespace PlaceDto {
    export type TypeEnum = 'HOME' | 'AWAY' | 'REMOTE';
    export const TypeEnum = {
        Home: 'HOME' as TypeEnum,
        Away: 'AWAY' as TypeEnum,
        Remote: 'REMOTE' as TypeEnum
    };
}


