/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PointsPerGameDto } from './pointsPerGameDto';
import { RecordDto } from './recordDto';
import { AccumulatedPointsPerGameDto } from './accumulatedPointsPerGameDto';


export interface PointsStatisticsResponseDto { 
    pointsPerGame: Array<PointsPerGameDto>;
    accumulatedPoints: Array<AccumulatedPointsPerGameDto>;
    maxGamePoints: Array<RecordDto>;
    minGamePoints: Array<RecordDto>;
}

