/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameDto } from './gameDto';


export interface RoundDto { 
    id: string;
    createDateTime: string;
    lastChangedDateTime: string;
    datetime: string;
    game: GameDto;
    attendees?: Array<Array<string>>;
    finalists?: Array<Array<string>>;
    events?: Array<Array<string>>;
}

