/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StreakDto } from './streakDto';
import { EventTypeStreakDto } from './eventTypeStreakDto';
import { SchockAusStreakDto } from './schockAusStreakDto';


export interface StreakStatisticsResponseDto { 
    noEventTypeStreaks: Array<EventTypeStreakDto>;
    eventTypeStreaks: Array<EventTypeStreakDto>;
    noPenaltyStreaks: Array<StreakDto>;
    penaltyStreaks: Array<StreakDto>;
    schockAusStreak: SchockAusStreakDto;
    attendanceStreaks: Array<StreakDto>;
}

