/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EventTypeOverviewDto } from '../../models/event-type-overview-dto';

export interface GetOverview_1$Params {
  context: string;
}

export function getOverview_1(http: HttpClient, rootUrl: string, params: GetOverview_1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EventTypeOverviewDto>>> {
  const rb = new RequestBuilder(rootUrl, getOverview_1.PATH, 'get');
  if (params) {
    rb.query('context', params.context, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EventTypeOverviewDto>>;
    })
  );
}

getOverview_1.PATH = '/event-type-overview';
