/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateGameDto {
  completed?: boolean;
  datetime?: string;
  hostedById?: string;
  placeOfAwayGame?: string;
  placeType: 'HOME' | 'AWAY' | 'REMOTE';
}
