/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CelebrationDto } from '../models/celebration-dto';
import { EventDto } from '../models/event-dto';
export interface CreateEventResponse {
  celebration?: CelebrationDto;
  event: EventDto;
  warning?: string;
}
