/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CelebrationDto } from '../models/celebration-dto';
import { RoundDto } from '../models/round-dto';
export interface CreateRoundResponse {
  celebration?: CelebrationDto;
  round: RoundDto;
}
