/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateEventDto {
  comment?: string;
  context: 'GAME' | 'ROUND';
  datetime?: string;
  eventTypeId: string;
  gameId?: string;
  multiplicatorValue?: number;
  playerId: string;
  roundId?: string;
}
