/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EventTypeOverviewDto {
  context: 'GAME' | 'ROUND';
  description: string;
  eventCount?: number;
  id: string;
  multiplicatorUnit?: string;
  penaltyUnit?: 'EURO' | 'BEER_CRATE';
  penaltyValue?: number;
}
