/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventTypeDto } from '../models/event-type-dto';
export interface EventTypeRevisionDto {
  context: 'GAME' | 'ROUND';
  createDateTime: string;
  description: string;
  eventType: EventTypeDto;
  hasComment: boolean;
  id: string;
  lastChangedDateTime: string;
  multiplicatorUnit?: string;
  penaltyUnit?: 'EURO' | 'BEER_CRATE';
  penaltyValue?: number;
  trigger?: 'START_NEW_ROUND' | 'SCHOCK_AUS' | 'SCHOCK_AUS_PENALTY';
  type: 'INSERT' | 'UPDATE' | 'REMOVE';
}
