/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EventTypeDetailDto {
  description: string;
  id: string;
  multiplicatorUnit?: string;
  trigger?: 'START_NEW_ROUND' | 'SCHOCK_AUS' | 'SCHOCK_AUS_PENALTY';
}
