/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventTypeDto } from '../models/event-type-dto';
import { GameDto } from '../models/game-dto';
import { PlayerDto } from '../models/player-dto';
import { RoundDto } from '../models/round-dto';
export interface EventDto {
  comment: string;
  context: 'GAME' | 'ROUND';
  createDateTime: string;
  datetime: string;
  eventType: EventTypeDto;
  game?: GameDto;
  id: string;
  lastChangedDateTime: string;
  multiplicatorValue: number;
  penaltyUnit?: 'EURO' | 'BEER_CRATE';
  penaltyValue?: number;
  player: PlayerDto;
  round?: RoundDto;
}
