/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventDetailDto } from '../models/event-detail-dto';
import { PlaceDto } from '../models/place-dto';
import { RoundDetailDto } from '../models/round-detail-dto';
export interface GameDetailDto {
  completed: boolean;
  datetime: string;
  events: Array<EventDetailDto>;
  excludeFromStatistics: boolean;
  id: string;
  place: PlaceDto;
  rounds: Array<RoundDetailDto>;
}
