/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventDto } from '../models/event-dto';
import { PlaceDto } from '../models/place-dto';
import { RoundDto } from '../models/round-dto';
export interface GameDto {
  completed: boolean;
  createDateTime: string;
  datetime: string;
  events?: Array<EventDto>;
  excludeFromStatistics: boolean;
  id: string;
  lastChangedDateTime: string;
  place?: PlaceDto;
  rounds?: Array<RoundDto>;
}
