/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GameDto } from '../models/game-dto';
export interface PlayerDto {
  active: boolean;
  createDateTime: string;
  hostedGames?: Array<GameDto>;
  id: string;
  isDeleted: boolean;
  lastChangedDateTime: string;
  name: string;
  registered: string;
}
