/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventDetailDto } from '../models/event-detail-dto';
import { PenaltyDto } from '../models/penalty-dto';
export interface RoundDetailDto {
  attendees: Array<string>;
  datetime: string;
  events: Array<EventDetailDto>;
  finalists: Array<string>;
  hasFinal: boolean;
  id: string;
  penalties: Array<PenaltyDto>;
  schockAusCount: number;
}
