/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GameDto } from '../models/game-dto';
export interface RoundDto {
  attendees?: Array<Array<any>>;
  createDateTime: string;
  datetime: string;
  events?: Array<Array<any>>;
  finalists?: Array<Array<any>>;
  game: GameDto;
  id: string;
  lastChangedDateTime: string;
}
