/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreatePenaltyDto } from '../models/create-penalty-dto';
export interface UpdateEventTypeDto {
  context?: 'GAME' | 'ROUND';
  createDateTime?: string;
  description?: string;
  hasComment?: boolean;
  lastChangedDateTime?: string;
  multiplicatorUnit?: string;
  penalty?: CreatePenaltyDto;
  trigger?: 'START_NEW_ROUND' | 'SCHOCK_AUS' | 'SCHOCK_AUS_PENALTY';
}
