/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameDetailDto } from '../../models/game-detail-dto';

export interface GetDetails_1$Params {
  id: string;
}

export function getDetails_1(http: HttpClient, rootUrl: string, params: GetDetails_1$Params, context?: HttpContext): Observable<StrictHttpResponse<GameDetailDto>> {
  const rb = new RequestBuilder(rootUrl, getDetails_1.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameDetailDto>;
    })
  );
}

getDetails_1.PATH = '/game/{id}/details';
