export * from './eventDetails.service';
import { EventDetailsService } from './eventDetails.service';
export * from './eventType.service';
import { EventTypeService } from './eventType.service';
export * from './eventTypeOverview.service';
import { EventTypeOverviewService } from './eventTypeOverview.service';
export * from './gameDetails.service';
import { GameDetailsService } from './gameDetails.service';
export * from './gameOverview.service';
import { GameOverviewService } from './gameOverview.service';
export * from './player.service';
import { PlayerService } from './player.service';
export * from './pushNotification.service';
import { PushNotificationService } from './pushNotification.service';
export * from './roundDetails.service';
import { RoundDetailsService } from './roundDetails.service';
export * from './statistics.service';
import { StatisticsService } from './statistics.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './userSettings.service';
import { UserSettingsService } from './userSettings.service';
export const APIS = [EventDetailsService, EventTypeService, EventTypeOverviewService, GameDetailsService, GameOverviewService, PlayerService, PushNotificationService, RoundDetailsService, StatisticsService, UserService, UserSettingsService];
