export * from './event.service';
import { EventService } from './event.service';
export * from './eventDetails.service';
import { EventDetailsService } from './eventDetails.service';
export * from './eventType.service';
import { EventTypeService } from './eventType.service';
export * from './eventTypeOverview.service';
import { EventTypeOverviewService } from './eventTypeOverview.service';
export * from './game.service';
import { GameService } from './game.service';
export * from './gameDetails.service';
import { GameDetailsService } from './gameDetails.service';
export * from './gameOverview.service';
import { GameOverviewService } from './gameOverview.service';
export * from './player.service';
import { PlayerService } from './player.service';
export * from './round.service';
import { RoundService } from './round.service';
export * from './roundDetails.service';
import { RoundDetailsService } from './roundDetails.service';
export const APIS = [EventService, EventDetailsService, EventTypeService, EventTypeOverviewService, GameService, GameDetailsService, GameOverviewService, PlayerService, RoundService, RoundDetailsService];
