/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EventTypeOverviewDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EventTypeOverviewServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param context 
     */
    getOverview(context: string, extraHttpRequestParams?: any): Observable<Array<EventTypeOverviewDto>>;

}
