/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateEventTypeDto } from '../model/models';
import { EventTypeDto } from '../model/models';
import { UpdateEventTypeDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EventTypeServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createEventTypeDto 
     */
    create(createEventTypeDto: CreateEventTypeDto, extraHttpRequestParams?: any): Observable<EventTypeDto>;

    /**
     * 
     * 
     */
    findAll(extraHttpRequestParams?: any): Observable<Array<EventTypeDto>>;

    /**
     * 
     * 
     * @param id 
     */
    remove(id: string, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @param id 
     * @param updateEventTypeDto 
     */
    update(id: string, updateEventTypeDto: UpdateEventTypeDto, extraHttpRequestParams?: any): Observable<EventTypeDto>;

}
