/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BulkCreateEventsDto } from '../model/models';
import { CreateDetailEventResponse } from '../model/models';
import { CreateEventDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EventDetailsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createEventDto 
     */
    create(createEventDto: CreateEventDto, extraHttpRequestParams?: any): Observable<CreateDetailEventResponse>;

    /**
     * 
     * 
     * @param bulkCreateEventsDto 
     */
    createMany(bulkCreateEventsDto: BulkCreateEventsDto, extraHttpRequestParams?: any): Observable<Array<CreateDetailEventResponse>>;

    /**
     * 
     * 
     * @param id 
     */
    remove(id: string, extraHttpRequestParams?: any): Observable<string>;

}
