/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateGameDto } from '../model/models';
import { GameDetailDto } from '../model/models';
import { UpdateGameDto } from '../model/models';
import { WhatsAppSentMessageDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GameDetailsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    completeGame(id: string, extraHttpRequestParams?: any): Observable<GameDetailDto>;

    /**
     * 
     * 
     * @param createGameDto 
     */
    create(createGameDto: CreateGameDto, extraHttpRequestParams?: any): Observable<GameDetailDto>;

    /**
     * 
     * 
     * @param id 
     */
    findOne(id: string, extraHttpRequestParams?: any): Observable<GameDetailDto>;

    /**
     * 
     * 
     * @param id 
     */
    publishPenalties(id: string, extraHttpRequestParams?: any): Observable<WhatsAppSentMessageDto>;

    /**
     * 
     * 
     * @param id 
     */
    remove(id: string, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @param id 
     * @param updateGameDto 
     */
    update(id: string, updateGameDto: UpdateGameDto, extraHttpRequestParams?: any): Observable<GameDetailDto>;

}
