/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GameWithPaymentInfoDto } from '../model/models';
import { PaymentBalanceDto } from '../model/models';
import { PaymentDto } from '../model/models';
import { UpdatePaymentDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PaymentServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getBalances(extraHttpRequestParams?: any): Observable<Array<PaymentBalanceDto>>;

    /**
     * 
     * 
     * @param gameId 
     */
    getByGameId(gameId: string, extraHttpRequestParams?: any): Observable<Array<PaymentDto>>;

    /**
     * 
     * 
     */
    getGameList(extraHttpRequestParams?: any): Observable<Array<GameWithPaymentInfoDto>>;

    /**
     * 
     * 
     * @param id 
     * @param updatePaymentDto 
     */
    update(id: string, updatePaymentDto: UpdatePaymentDto, extraHttpRequestParams?: any): Observable<PaymentDto>;

}
