/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreatePlayerDto } from '../model/models';
import { PlayerDto } from '../model/models';
import { UpdatePlayerDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PlayerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createPlayerDto 
     */
    create(createPlayerDto: CreatePlayerDto, extraHttpRequestParams?: any): Observable<PlayerDto>;

    /**
     * 
     * 
     */
    findAll(extraHttpRequestParams?: any): Observable<Array<PlayerDto>>;

    /**
     * 
     * 
     * @param id 
     */
    findOne(id: string, extraHttpRequestParams?: any): Observable<PlayerDto>;

    /**
     * 
     * 
     * @param id 
     */
    getPlayerByUserId(id: string, extraHttpRequestParams?: any): Observable<PlayerDto>;

    /**
     * 
     * 
     * @param id 
     */
    remove(id: string, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @param id 
     * @param updatePlayerDto 
     */
    update(id: string, updatePlayerDto: UpdatePlayerDto, extraHttpRequestParams?: any): Observable<PlayerDto>;

}
