/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PushSubscriptionDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PushNotificationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getPublicKey(extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     */
    send(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param pushSubscriptionDto 
     */
    subscribe(pushSubscriptionDto: PushSubscriptionDto, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @param endpoint 
     */
    unsubscribe(endpoint: string, extraHttpRequestParams?: any): Observable<string>;

}
