/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateDetailRoundResponse } from '../model/models';
import { CreateRoundDto } from '../model/models';
import { RoundDetailDto } from '../model/models';
import { UpdateAttendanceDto } from '../model/models';
import { UpdateFinalistsDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RoundDetailsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createRoundDto 
     */
    create(createRoundDto: CreateRoundDto, extraHttpRequestParams?: any): Observable<CreateDetailRoundResponse>;

    /**
     * 
     * 
     * @param gameId 
     */
    getByGameId(gameId: string, extraHttpRequestParams?: any): Observable<Array<RoundDetailDto>>;

    /**
     * 
     * 
     * @param id 
     */
    getDetails(id: string, extraHttpRequestParams?: any): Observable<RoundDetailDto>;

    /**
     * 
     * 
     * @param id 
     */
    remove(id: string, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @param id 
     * @param updateAttendanceDto 
     */
    updateAttendees(id: string, updateAttendanceDto: UpdateAttendanceDto, extraHttpRequestParams?: any): Observable<RoundDetailDto>;

    /**
     * 
     * 
     * @param id 
     * @param updateFinalistsDto 
     */
    updateFinalists(id: string, updateFinalistsDto: UpdateFinalistsDto, extraHttpRequestParams?: any): Observable<RoundDetailDto>;

}
