/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AttendancesStatisticsResponseDto } from '../model/models';
import { CountByNameDto } from '../model/models';
import { EventTypeStatisticsRequestDto } from '../model/models';
import { EventTypesStatisticsResponseDto } from '../model/models';
import { GameIdsWithDatetimeDto } from '../model/models';
import { GamesAndRoundsStatisticsResponseDto } from '../model/models';
import { HostStatisticsResponseDto } from '../model/models';
import { LiveGameStatisticsRequestDto } from '../model/models';
import { LiveGameStatisticsResponseDto } from '../model/models';
import { PenaltyStatisticsResponseDto } from '../model/models';
import { PointsStatisticsResponseDto } from '../model/models';
import { StatisticsRequestDto } from '../model/models';
import { StreakStatisticsResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface StatisticsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    allGames(extraHttpRequestParams?: any): Observable<Array<GameIdsWithDatetimeDto>>;

    /**
     * 
     * 
     * @param statisticsRequestDto 
     */
    attendancesStatistics(statisticsRequestDto: StatisticsRequestDto, extraHttpRequestParams?: any): Observable<AttendancesStatisticsResponseDto>;

    /**
     * 
     * 
     * @param eventTypeStatisticsRequestDto 
     */
    eventTypeCountsByPlayer(eventTypeStatisticsRequestDto: EventTypeStatisticsRequestDto, extraHttpRequestParams?: any): Observable<Array<CountByNameDto>>;

    /**
     * 
     * 
     * @param statisticsRequestDto 
     */
    eventTypeStatistics(statisticsRequestDto: StatisticsRequestDto, extraHttpRequestParams?: any): Observable<EventTypesStatisticsResponseDto>;

    /**
     * 
     * 
     * @param statisticsRequestDto 
     */
    gamesAndRoundsStatistics(statisticsRequestDto: StatisticsRequestDto, extraHttpRequestParams?: any): Observable<GamesAndRoundsStatisticsResponseDto>;

    /**
     * 
     * 
     * @param statisticsRequestDto 
     */
    hostStatistics(statisticsRequestDto: StatisticsRequestDto, extraHttpRequestParams?: any): Observable<HostStatisticsResponseDto>;

    /**
     * 
     * 
     * @param liveGameStatisticsRequestDto 
     */
    liveGameStatistics(liveGameStatisticsRequestDto: LiveGameStatisticsRequestDto, extraHttpRequestParams?: any): Observable<LiveGameStatisticsResponseDto>;

    /**
     * 
     * 
     * @param statisticsRequestDto 
     */
    penaltyStatistics(statisticsRequestDto: StatisticsRequestDto, extraHttpRequestParams?: any): Observable<PenaltyStatisticsResponseDto>;

    /**
     * 
     * 
     * @param statisticsRequestDto 
     */
    pointsStatistics(statisticsRequestDto: StatisticsRequestDto, extraHttpRequestParams?: any): Observable<PointsStatisticsResponseDto>;

    /**
     * 
     * 
     * @param statisticsRequestDto 
     */
    streakStatistics(statisticsRequestDto: StatisticsRequestDto, extraHttpRequestParams?: any): Observable<StreakStatisticsResponseDto>;

}
