/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UpdateUserSettingsDto } from '../model/models';
import { UserSettingsDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserSettingsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param updateUserSettingsDto 
     */
    createOrUpdate(updateUserSettingsDto: UpdateUserSettingsDto, extraHttpRequestParams?: any): Observable<UserSettingsDto>;

    /**
     * 
     * 
     * @param userId 
     */
    findByUserId(userId: string, extraHttpRequestParams?: any): Observable<UserSettingsDto>;

}
