/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { OutstandingPenaltyDto } from '../model/models';
import { UserPaymentDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserPaymentServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getByUserId(extraHttpRequestParams?: any): Observable<Array<UserPaymentDto>>;

    /**
     * 
     * 
     */
    getOutstandingPenaltiesByUserId(extraHttpRequestParams?: any): Observable<Array<OutstandingPenaltyDto>>;

    /**
     * 
     * 
     */
    getQrCodeByUserId(extraHttpRequestParams?: any): Observable<string>;

}
