/**
 * schocken-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { QrCodeDto } from '../model/models';
import { WhatsAppChatInfoDto } from '../model/models';
import { WhatsAppClientLogHistoryDto } from '../model/models';
import { WhatsAppClientStatusDto } from '../model/models';
import { WhatsAppSentMessageDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface WhatsappServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getChats(extraHttpRequestParams?: any): Observable<Array<WhatsAppChatInfoDto>>;

    /**
     * 
     * 
     */
    getClientStatus(extraHttpRequestParams?: any): Observable<WhatsAppClientStatusDto>;

    /**
     * 
     * 
     */
    getLogHistory(extraHttpRequestParams?: any): Observable<Array<WhatsAppClientLogHistoryDto>>;

    /**
     * 
     * 
     */
    initialize(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    latestQrCode(extraHttpRequestParams?: any): Observable<QrCodeDto>;

    /**
     * 
     * 
     */
    purge(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    sendTestMessage(extraHttpRequestParams?: any): Observable<WhatsAppSentMessageDto>;

}
