/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateEventTypeDto } from '../../models/create-event-type-dto';
import { EventTypeDto } from '../../models/event-type-dto';

export interface Create_4$Params {
      body: CreateEventTypeDto
}

export function create_4(http: HttpClient, rootUrl: string, params: Create_4$Params, context?: HttpContext): Observable<StrictHttpResponse<EventTypeDto>> {
  const rb = new RequestBuilder(rootUrl, create_4.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EventTypeDto>;
    })
  );
}

create_4.PATH = '/event-type';
