/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EventTypeDto } from '../../models/event-type-dto';

export interface FindAll_4$Params {
}

export function findAll_4(http: HttpClient, rootUrl: string, params?: FindAll_4$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EventTypeDto>>> {
  const rb = new RequestBuilder(rootUrl, findAll_4.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EventTypeDto>>;
    })
  );
}

findAll_4.PATH = '/event-type';
