/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EventTypeDto } from '../../models/event-type-dto';
import { UpdateEventTypeDto } from '../../models/update-event-type-dto';

export interface Update_4$Params {
  id: string;
      body: UpdateEventTypeDto
}

export function update_4(http: HttpClient, rootUrl: string, params: Update_4$Params, context?: HttpContext): Observable<StrictHttpResponse<EventTypeDto>> {
  const rb = new RequestBuilder(rootUrl, update_4.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EventTypeDto>;
    })
  );
}

update_4.PATH = '/event-type/{id}';
