/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { EventTypeOverviewDto } from '../models/event-type-overview-dto';
import { getOverview_1 } from '../fn/event-type-overview/get-overview-1';
import { GetOverview_1$Params } from '../fn/event-type-overview/get-overview-1';

@Injectable({ providedIn: 'root' })
export class EventTypeOverviewService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getOverview_1()` */
  static readonly GetOverview_1Path = '/event-type-overview';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOverview_1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOverview_1$Response(params: GetOverview_1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EventTypeOverviewDto>>> {
    return getOverview_1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOverview_1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOverview_1(params: GetOverview_1$Params, context?: HttpContext): Observable<Array<EventTypeOverviewDto>> {
    return this.getOverview_1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EventTypeOverviewDto>>): Array<EventTypeOverviewDto> => r.body)
    );
  }

}
