/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addFinalist } from '../fn/round/add-finalist';
import { AddFinalist$Params } from '../fn/round/add-finalist';
import { create_1 } from '../fn/round/create-1';
import { Create_1$Params } from '../fn/round/create-1';
import { CreateRoundResponse } from '../models/create-round-response';
import { findAll_1 } from '../fn/round/find-all-1';
import { FindAll_1$Params } from '../fn/round/find-all-1';
import { findOne_1 } from '../fn/round/find-one-1';
import { FindOne_1$Params } from '../fn/round/find-one-1';
import { getDetails } from '../fn/round/get-details';
import { GetDetails$Params } from '../fn/round/get-details';
import { remove_1 } from '../fn/round/remove-1';
import { Remove_1$Params } from '../fn/round/remove-1';
import { removeFinalist } from '../fn/round/remove-finalist';
import { RemoveFinalist$Params } from '../fn/round/remove-finalist';
import { RoundDetailDto } from '../models/round-detail-dto';
import { RoundDto } from '../models/round-dto';
import { update_1 } from '../fn/round/update-1';
import { Update_1$Params } from '../fn/round/update-1';
import { updateAttendees } from '../fn/round/update-attendees';
import { UpdateAttendees$Params } from '../fn/round/update-attendees';

@Injectable({ providedIn: 'root' })
export class RoundService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findAll_1()` */
  static readonly FindAll_1Path = '/round';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAll_1()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAll_1$Response(params?: FindAll_1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoundDto>>> {
    return findAll_1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAll_1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAll_1(params?: FindAll_1$Params, context?: HttpContext): Observable<Array<RoundDto>> {
    return this.findAll_1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RoundDto>>): Array<RoundDto> => r.body)
    );
  }

  /** Path part for operation `create_1()` */
  static readonly Create_1Path = '/round';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create_1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create_1$Response(params: Create_1$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateRoundResponse>> {
    return create_1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create_1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create_1(params: Create_1$Params, context?: HttpContext): Observable<CreateRoundResponse> {
    return this.create_1$Response(params, context).pipe(
      map((r: StrictHttpResponse<CreateRoundResponse>): CreateRoundResponse => r.body)
    );
  }

  /** Path part for operation `findOne_1()` */
  static readonly FindOne_1Path = '/round/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findOne_1()` instead.
   *
   * This method doesn't expect any request body.
   */
  findOne_1$Response(params: FindOne_1$Params, context?: HttpContext): Observable<StrictHttpResponse<RoundDto>> {
    return findOne_1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findOne_1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findOne_1(params: FindOne_1$Params, context?: HttpContext): Observable<RoundDto> {
    return this.findOne_1$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoundDto>): RoundDto => r.body)
    );
  }

  /** Path part for operation `remove_1()` */
  static readonly Remove_1Path = '/round/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `remove_1()` instead.
   *
   * This method doesn't expect any request body.
   */
  remove_1$Response(params: Remove_1$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return remove_1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `remove_1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  remove_1(params: Remove_1$Params, context?: HttpContext): Observable<string> {
    return this.remove_1$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `update_1()` */
  static readonly Update_1Path = '/round/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update_1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update_1$Response(params: Update_1$Params, context?: HttpContext): Observable<StrictHttpResponse<RoundDto>> {
    return update_1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update_1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update_1(params: Update_1$Params, context?: HttpContext): Observable<RoundDto> {
    return this.update_1$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoundDto>): RoundDto => r.body)
    );
  }

  /** Path part for operation `getDetails()` */
  static readonly GetDetailsPath = '/round/{id}/details';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDetails()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDetails$Response(params: GetDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<RoundDetailDto>> {
    return getDetails(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDetails$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDetails(params: GetDetails$Params, context?: HttpContext): Observable<RoundDetailDto> {
    return this.getDetails$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoundDetailDto>): RoundDetailDto => r.body)
    );
  }

  /** Path part for operation `updateAttendees()` */
  static readonly UpdateAttendeesPath = '/round/{id}/attendees';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateAttendees()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAttendees$Response(params: UpdateAttendees$Params, context?: HttpContext): Observable<StrictHttpResponse<RoundDto>> {
    return updateAttendees(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateAttendees$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAttendees(params: UpdateAttendees$Params, context?: HttpContext): Observable<RoundDto> {
    return this.updateAttendees$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoundDto>): RoundDto => r.body)
    );
  }

  /** Path part for operation `removeFinalist()` */
  static readonly RemoveFinalistPath = '/round/{roundId}/finalists/{playerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeFinalist()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeFinalist$Response(params: RemoveFinalist$Params, context?: HttpContext): Observable<StrictHttpResponse<RoundDto>> {
    return removeFinalist(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeFinalist$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeFinalist(params: RemoveFinalist$Params, context?: HttpContext): Observable<RoundDto> {
    return this.removeFinalist$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoundDto>): RoundDto => r.body)
    );
  }

  /** Path part for operation `addFinalist()` */
  static readonly AddFinalistPath = '/round/{roundId}/finalists/{playerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addFinalist()` instead.
   *
   * This method doesn't expect any request body.
   */
  addFinalist$Response(params: AddFinalist$Params, context?: HttpContext): Observable<StrictHttpResponse<RoundDto>> {
    return addFinalist(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addFinalist$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  addFinalist(params: AddFinalist$Params, context?: HttpContext): Observable<RoundDto> {
    return this.addFinalist$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoundDto>): RoundDto => r.body)
    );
  }

}
