/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { CreateEventDto } from './models/create-event-dto';
export { CreateEventTypeDto } from './models/create-event-type-dto';
export { CreateGameDto } from './models/create-game-dto';
export { CreatePlayerDto } from './models/create-player-dto';
export { CreateRoundDto } from './models/create-round-dto';
export { GameDto } from './models/game-dto';
export { GameOverviewDto } from './models/game-overview-dto';
export { PenaltyDto } from './models/penalty-dto';
export { PlaceDto } from './models/place-dto';
export { PlayerDto } from './models/player-dto';
export { UpdateAttendanceDto } from './models/update-attendance-dto';
export { UpdateEventDto } from './models/update-event-dto';
export { UpdateEventTypeDto } from './models/update-event-type-dto';
export { UpdateGameDto } from './models/update-game-dto';
export { UpdatePlayerDto } from './models/update-player-dto';
export { UpdateRoundDto } from './models/update-round-dto';
