/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { PlayerService } from './services/player.service';
export { RoundService } from './services/round.service';
export { GameService } from './services/game.service';
export { GameOverviewService } from './services/game-overview.service';
export { EventService } from './services/event.service';
export { EventTypeService } from './services/event-type.service';
export { EventTypeOverviewService } from './services/event-type-overview.service';
