/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoundDto } from '../../models/round-dto';

export interface AddFinalist$Params {
  roundId: string;
  playerId: string;
}

export function addFinalist(http: HttpClient, rootUrl: string, params: AddFinalist$Params, context?: HttpContext): Observable<StrictHttpResponse<RoundDto>> {
  const rb = new RequestBuilder(rootUrl, addFinalist.PATH, 'patch');
  if (params) {
    rb.path('roundId', params.roundId, {});
    rb.path('playerId', params.playerId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RoundDto>;
    })
  );
}

addFinalist.PATH = '/round/{roundId}/finalists/{playerId}';
